data:
  UL16_postVFP:
    nanoAOD:
      F: /BTagCSV/Run2016F-UL2016_MiniAODv2_NanoAODv9-v1/NANOAOD
      G: /BTagCSV/Run2016G-UL2016_MiniAODv2_NanoAODv9-v1/NANOAOD
    picoAOD:
      F:
        count: 4852270.0
        files:
        - root://cmsdata.phys.cmu.edu//store/group/HH4b/Run2/opendata_project/data2016F/picoAOD.root
        missing: {}
        saved_events: 45436
        total_events: 4852270
      G:
        count: 100826567.0
        files:
        - root://cmsdata.phys.cmu.edu//store/group/HH4b/Run2/opendata_project/data2016G/picoAOD.root
        missing: {}
        saved_events: 818505
        sumw2_raw: 100826567
        sumw_raw: 100826567
        total_events: 100826567
data_3b_for_mixed:
  '2016':
    picoAOD:
      FvT_file_kfold_template: root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2016_3b/FvT_3bDvTMix4bDvT_vXXX_newSBDefSeedAll45.root
      FvT_file_template: root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2016_3b/FvT_3bDvTMix4bDvT_vXXX_newSBDef.root
      FvT_name_kfold_template: FvT_3bDvTMix4bDvT_vXXX_newSBDefSeedAve
      FvT_name_template: FvT_3bDvTMix4bDvT_vXXX_newSBDef
      JCM_load_template: 3bDvTMix4bDvT_vXXX
      files:
      - root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2016_3b/picoAOD_3b_wJCM_newSBDef.root
  '2017':
    picoAOD:
      FvT_file_kfold_template: root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2017_3b/FvT_3bDvTMix4bDvT_vXXX_newSBDefSeedAll45.root
      FvT_file_template: root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2017_3b/FvT_3bDvTMix4bDvT_vXXX_newSBDef.root
      FvT_name_kfold_template: FvT_3bDvTMix4bDvT_vXXX_newSBDefSeedAve
      FvT_name_template: FvT_3bDvTMix4bDvT_vXXX_newSBDef
      JCM_load_template: 3bDvTMix4bDvT_vXXX
      files:
      - root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2017_3b/picoAOD_3b_wJCM_newSBDef.root
  '2018':
    picoAOD:
      FvT_file_kfold_template: root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2018_3b/FvT_3bDvTMix4bDvT_vXXX_newSBDefSeedAll45.root
      FvT_file_template: root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2018_3b/FvT_3bDvTMix4bDvT_vXXX_newSBDef.root
      FvT_name_kfold_template: FvT_3bDvTMix4bDvT_vXXX_newSBDefSeedAve
      FvT_name_template: FvT_3bDvTMix4bDvT_vXXX_newSBDef
      JCM_load_template: 3bDvTMix4bDvT_vXXX
      files:
      - root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2018_3b/picoAOD_3b_wJCM_newSBDef.root
  nSamples: 15
  use_kfold: true
